package terminal

import (
	"fmt"
	"strings"

	"chronicle/internal/query/lexer"
)

func printHelp(version string) {
	fmt.Println(dim + "Chronicle v" + version + reset)
	fmt.Println()

	// ---------------- WRITING ----------------
	fmt.Println(bold + "Remembering" + reset)
	fmt.Println("  rem [@type] [#tags...] <text>")
	fmt.Println("  remember [@type] [#tags...] <text>")
	fmt.Println()
	fmt.Println("  The type and the tags may come in either order, and everything")
	fmt.Println("  after them is the entry, stored exactly as you typed it.")
	fmt.Println()
	fmt.Println("  Types:")
	fmt.Println("    @note (@n)   @idea (@i)   @question (@q)")
	fmt.Println("    @learning (@l)   @important (@imp)")
	fmt.Println()
	fmt.Println("  Without a type the entry is stored as a note. An unknown type is")
	fmt.Println("  an error rather than a silent note.")
	fmt.Println()
	fmt.Println("  Examples:")
	fmt.Println("    rem Read chapter 3")
	fmt.Println("    rem @learning #math #analysis Uniform convergence theorem")
	fmt.Println("    rem #math #analysis @learning same thing, markers swapped")
	fmt.Println("    remember @idea #project Use an append only log")
	fmt.Println()
	fmt.Println("  Entry text is never interpreted, so punctuation, symbols and")
	fmt.Println("  other alphabets are all kept:")
	fmt.Println("    rem cost is 50% of budget")
	fmt.Println("    rem see http://example.com and/or ask")
	fmt.Println("    rem café naïve 🎉")
	fmt.Println()
	fmt.Println("  A # or @ inside the text is just text. Only the markers before")
	fmt.Println("  the entry are read as a type and tags:")
	fmt.Println("    rem #work meeting notes #work   ->  tag work, text \"meeting notes #work\"")
	fmt.Println()
	fmt.Println("  Wrap the whole entry in quotes to keep it literal. The quotes are")
	fmt.Println("  removed, and nothing inside them is read as a marker:")
	fmt.Println("    rem \"@todo buy milk\"      ->  note, text \"@todo buy milk\"")
	fmt.Println("    rem @idea \"Read chapter 3\"  ->  idea, text \"Read chapter 3\"")
	fmt.Println()

	fmt.Println(bold + "Revising" + reset)
	fmt.Println("  revise [@type] [#tags...] where <predicate>")
	fmt.Println()
	fmt.Println("  Changes every entry the predicate matches. A type replaces the old")
	fmt.Println("  one, tags are added to the existing tags, and the entry text is left")
	fmt.Println("  alone. Revising updates the entry's time to now.")
	fmt.Println()
	fmt.Println("  Examples:")
	fmt.Println("    revise @important where tags[deadline]")
	fmt.Println("    revise #go where contains[\"golang\"]")
	fmt.Println("    revise @idea #later where id[3,7]")
	fmt.Println("    revise @idea #later where all")
	fmt.Println()

	fmt.Println(bold + "Forgetting" + reset)
	fmt.Println("  forget <predicate>")
	fmt.Println()
	fmt.Println("  Shows what matched, then asks before deleting. Answer y to delete")
	fmt.Println("  all of them, n to cancel, or a list of ids to delete only those.")
	fmt.Println()
	fmt.Println("  Examples:")
	fmt.Println("    forget id[3,7]")
	fmt.Println("    forget contains[\"draft\"]")
	fmt.Println("    forget type[note] AND date < \"2025\"")
	fmt.Println()

	// ---------------- RECALL ----------------
	fmt.Println(bold + "Recall" + reset)
	fmt.Println("  recall <predicate>")
	fmt.Println()

	// ---------------- QUERY SYNTAX ----------------
	fmt.Println(bold + "Predicates" + reset)
	fmt.Println("  all                every entry")
	fmt.Println("  contains[\"a\",\"b\"]  entries whose text holds any of these words")
	fmt.Println("  type[note,idea]    entries of any of these types")
	fmt.Println("  tags[go,db]        entries carrying any of these tags")
	fmt.Println("  id[3,7]            entries with these ids, the number shown in { }")
	fmt.Println("  date <op> \"...\"    the day the entry was written")
	fmt.Println("  time <op> \"...\"    the time of day it was written")
	fmt.Println("  len <op> <number>  how many characters the entry holds")
	fmt.Println()
	fmt.Println("  Predicates can be joined with AND and OR, and grouped with ( ).")
	fmt.Println("  AND binds tighter than OR.")
	fmt.Println()

	fmt.Println(bold + "Comparison Operators" + reset)
	fmt.Println("  =   equal")
	fmt.Println("  !=  not equal")
	fmt.Println("  >   greater than")
	fmt.Println("  <   less than")
	fmt.Println("  >=  greater or equal")
	fmt.Println("  <=  less or equal")
	fmt.Println()

	fmt.Println(bold + "Logical Operators" + reset)
	fmt.Println("  AND")
	fmt.Println("  OR")
	fmt.Println()

	fmt.Println(bold + "Reserved Words" + reset)
	fmt.Println("  " + strings.Join(lexer.ReservedWords(), "  "))
	fmt.Println()
	fmt.Println("  These belong to the query language, so they cannot appear inside")
	fmt.Println("  type[...] or tags[...]. A tag with one of these names can still be")
	fmt.Println("  written, it just cannot be searched for.")
	fmt.Println()

	fmt.Println(bold + "Examples" + reset)
	fmt.Println("  recall all")
	fmt.Println("  recall contains[\"golang\"]")
	fmt.Println("  recall contains[\"golang\"] AND type[note]")
	fmt.Println("  recall tags[go]")
	fmt.Println("  recall tags[go,database]")
	fmt.Println("  recall type[note,idea]")
	fmt.Println("  recall id[3]")
	fmt.Println("  recall id[3,7,12]")
	fmt.Println("  recall len > 100")
	fmt.Println("  recall time > \"7 PM\"")
	fmt.Println("  recall date >= \"2026-04-01\"")
	fmt.Println()

	fmt.Println("  Lists use OR semantics:")
	fmt.Println("    type[note,idea]")
	fmt.Println("    tags[go,database]")
	fmt.Println("    id[3,7,12]")
	fmt.Println("    contains[\"go\",\"database\"]")
	fmt.Println()

	fmt.Println("  Require multiple conditions using AND:")
	fmt.Println("    tags[go] AND tags[database]")
	fmt.Println("    contains[\"go\"] AND contains[\"database\"]")
	fmt.Println()

	// ---------------- TIME & DATE ----------------
	fmt.Println(bold + "Time & Date Formats" + reset)
	fmt.Println("  Time:")
	fmt.Println("    \"7 PM\"        the 7 PM hour")
	fmt.Println("    \"07:30 PM\"    that minute")
	fmt.Println("    \"19:30\"       24 hour clock")
	fmt.Println("    \"19:30:45\"    to the second")
	fmt.Println()

	fmt.Println("  Date:")
	fmt.Println("    \"10-04-2026\"  DD-MM-YYYY")
	fmt.Println("    \"2026-04-10\"  YYYY-MM-DD")
	fmt.Println("    \"04-2026\"     a whole month")
	fmt.Println("    \"2026-04\"     a whole month")
	fmt.Println("    \"2026\"        a whole year")
	fmt.Println()
	fmt.Println("  - and / both work, and the four digit year tells Chronicle")
	fmt.Println("  which end is which, so 10/04/2026 and 2026-04-10 are the same day.")
	fmt.Println()

	fmt.Println(bold + "How Date & Time Compare" + reset)
	fmt.Println("  A value covers a span as wide as the detail you give.")
	fmt.Println("  \"7 PM\" covers 19:00:00 to 19:59:59, \"2026\" covers the whole year.")
	fmt.Println()
	fmt.Println("    =    inside the span          time = \"7 PM\"   matches 7:30 PM")
	fmt.Println("    !=   outside the span")
	fmt.Println("    >    after the span starts    time > \"7 PM\"   matches 7:30 PM")
	fmt.Println("    >=   at or after the start")
	fmt.Println("    <    before the span starts   time < \"7 PM\"   excludes 7:30 PM")
	fmt.Println("    <=   at or before the end     time <= \"7 PM\"  matches 7:30 PM")
	fmt.Println()
	fmt.Println("  Watch out:")
	fmt.Println("    date > \"2026\" still matches 2026, since the year starts before its")
	fmt.Println("    later days. For entries after a whole year use date >= \"2027\".")
	fmt.Println("    The same holds for a month: date > \"2026-04\" still matches April.")
	fmt.Println()
	fmt.Println("    The year must be written in full, since it is what tells day and")
	fmt.Println("    year apart. \"10-04-26\" is rejected, \"10-04-2026\" is not.")
	fmt.Println()
	fmt.Println("    A value that is not a real date or time is rejected rather than ignored,")
	fmt.Println("    so date > \"yesterday\" and time > \"25:00\" are errors, not empty results.")
	fmt.Println()

	// ---------------- SESSION ----------------
	fmt.Println(bold + "Session" + reset)
	fmt.Println("  help      show this text")
	fmt.Println("  version   show the Chronicle version")
	fmt.Println("  clear     clear the screen")
	fmt.Println("  index     print the search index built at startup")
	fmt.Println("  exit      leave Chronicle")
	fmt.Println("  quit      leave Chronicle")
	fmt.Println()
}
